baseURL = 'https://joshuamauldin.com/'
title = 'Joshua Mauldin'
theme = 'hugo-book'
copyright = '2023, Joshua Mauldin.'
enableRobotsTXT = true
removePathAccents = true

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

# Image processing
[imaging]
  anchor = 'Smart'
  bgColor = '#333333'
  hint = 'photo'
  quality = 60
  imageMaxWidth = "1500px"
  imageMaxHeight = "1500px"
  resampleFilter = 'Box'
  [imaging.exif]
    disableDate = true
    disableLatLong = true
    excludeFields = ''
    includeFields = ''

[params]
  # Theme Colors
  themeColorDark = "#000000"
  themeColorLight = "#FFFCFA"

  # Book Settings
  BookTheme = 'auto'
  BookToC = false
  BookMenuBundle = '/menu'
  BookSection = 'journal'
  BookRepo = 'https://github.com/alex-shpak/hugo-book'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false
  
  # Experimental Features
  BookServiceWorker = false
  BookTranslatedOnly = false

# Uncomment below settings if needed
#  BookLogo = 'skull.svg'
#  BookCommitPath = 'commit'
#  BookEditPath = 'edit/main/exampleSite'
#  BookPortableLinks = true
