baseURL = 'https://joshuamauldin.com/'
title = 'Joshua Mauldin'
theme = 'hugo-book'
copyright = '2023, Joshua Mauldin'
enableRobotsTXT = true
removePathAccents = true

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Theme Colors
  themeColorDark = "#000000"
  themeColorLight = "#FFFCFA"

  # Book Settings
  BookTheme = 'auto'
  BookToC = false
  BookMenuBundle = '/menu'
  BookSection = 'journal'
  BookRepo = 'https://github.com/alex-shpak/hugo-book'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false
  
  # Experimental Features
  BookServiceWorker = true
  BookTranslatedOnly = false

# Uncomment below settings if needed
#  BookPortableLinks = true
